name: CI-CD

on:
  push:
    branches: ["main"]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.2.2

    - name: Docker Hub Login
      uses: docker/login-action@v3.3.0
      with:
        username: ${{secrets.DOCKERHUB_USER}}
        password: ${{secrets.DOCKERHUB_PASSWD}}
      
    - name: DockerImage Build and Push
      uses: docker/build-push-action@v6.9.0
      with:
        context: ./src
        file: ./src/Dockerfile
        push: true
        tags: |
          julioesf/kube-news:${{github.run_number}}
          julioesf/kube-news:latest
          
  CD:
    runs-on: ubuntu-latest
    needs: CI

    steps:
    - uses: actions/checkout@v4.2.2

    - name: Kubernetes Set Context
      uses: Azure/k8s-set-context@v3.0
      with:
        method: kubeconfig
        kubeconfig: ${{secrets.KUBE_CONFIG}}
        context: ${{secrets.KUBE_CONTEXT}}
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1 # ajuste conforme sua região

    - name: Update Route 53 record
      run: |
        aws route53 change-resource-record-sets --hosted-zone-id ZONE_ID \
          --change-batch '{
            "Changes": [
              {
                "Action": "UPSERT",
                "ResourceRecordSet": {
                  "Name": "kubenews.masterinfra.net.",
                    "Type": "A",
                    "TTL": 300,
                    "ResourceRecords": [
                      {
                        "Value": "198.244.200.204"
                      }
                    ]
                  }
                }
              ]
            }'
        env:
          ZONE_ID: "Z02107982DFK4A9701QHT"
          IP_ADDRESS: "198.244.200.204"
    
    - name: Kubernetes Deployment
      uses: Azure/k8s-deploy@v4.9
      with:
        images: julioesf/kube-news:${{github.run_number}}
        namespace: kubenews
        manifests: |
          k8s/deployment.yaml
        

    
