name: CI-CD

on:
  push:
    branches: ["main"]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.2.2

    - name: Docker Hub Login
      uses: docker/login-action@v3.3.0
      with:
        username: ${{secrets.DOCKERHUB_USER}}
        password: ${{secrets.DOCKERHUB_PASSWD}}
      
    - name: DockerImage Build
      uses: docker/build-push-action@v6.9.0
      with:
        context: ./src
        file: ./src/Dockerfile
        push: true
        tags: |
          julioesf/kube-news:${{github.run_number}}
          julioesf/kube-news:latest
          
